### PR TITLE
Update getting-started with Adam's blog post

### PR DESCRIPTION
**Pull request by falexwolf**
Integrate https://adamgayoso.com/posts/ten_min_to_adata/ into the getting-started tutorial.

### CODE REVIEW

**Comment by falexwolf** [comment]
@adamgayoso, could you check whether everything is correct?

**Comment by ivirshup** [comment]
We could also put that off until we've got a better notebook rendering system set up

**Comment by falexwolf** [comment]
If you're not seeing problems with the content, I don't see any reason to wait with merging if Adam would also be fine with how his material got integrated.

It's just an improvement to the main getting-started tutorial that's already linked on the main docs: https://anndata.readthedocs.io/en/latest/tutorials.html

I think it addresses Malte's years-long request for a 5 min-to-anndata tutorial at least to some degree.

But @LuckyMD will be the better person to make that call! ☺️

**Comment by ivirshup** [comment]
I've cut down on the notes at the top a bit.

I felt like they were getting into the weeds on topics which aren't critical to a very quick introduction to anndata.

**Comment by LuckyMD** [comment]
I love this blog post! Awesome that's something like this is finally in the tutorials!

I haven't checked the jupyter notebook, but I think there was something about subsetting `.obs` by booleans or based on other `.obs` covariates that had some quirks, no? Also, if you could add sth like `.groupby` calls on `.obs` that would be quite nice.

Also, maybe some information on `.rename_categories` and the effects thereof would be useful (changing stored `rank_genes_groups` outputs).

**Pull request merged**
